Repository Aniketsonii/Learning, pull requests merged in 2022-10, with the labels that each got.

#1 Create blackjackgame.py
  blackjackgame.py
Labels: good first issue

#7 N-queen
  N-queen.py
Labels: enhancement

#19 Create easy way to find prime.py
  easy way to find prime.py
Labels: hacktoberfest-accepted

#18 Added Binary Tree Inversion
  invert-binary-tree.cpp
Labels: hacktoberfest-accepted
